### PR TITLE
stitching of messages for proper prompt creation in conversation

### LINKED ISSUE #69: `generations` endpoint in chat services is not using past messages as prompt in successive turns
[here](https://github.com/premAI-io/prem-services/blob/dd36f1fd61dfe2c3800622d87464b743782d5d04/cht-llama-v2/models.py#L52) 
```message = messages[-1]["content"]``` causes the generate function to use only the current turn message from user as prompt for generating new responses.

### PR DESCRIPTION
**Pull request by biswaroop1547**
fixes #69

### CODE REVIEW

**Comment by casperdcl** [comment]
I think it's better to use a fork for PRs (otherwise some CI tricker will be required to avoid duplicate runs)

**Comment by biswaroop1547** [comment]
> I think it's better to use a fork for PRs (otherwise some CI config trickery will be required to avoid duplicate runs)

@casperdcl specially when we don't want to do image build and push right? currently I made some changes where I want new image to be created and pushed - for this also should I fork first and make a PR? if yes then will keep that in mind!

same applies for hotfixes?

**Comment by casperdcl** [comment]
Yes should fork & PR in all cases :)

**Comment by biswaroop1547** [comment]
got it! thanks!

**Pull request closed without merging**
